/**
 * WHAT: Prepares, validates and deploys one paired Focus Mission release.
 * WHY: Public versions, history, source evidence and production builds must agree.
 * HOW: Review actual Git diffs, bind notes to source hashes, validate clean
 * archives, then commit/tag only generated metadata and publish the tested build.
 * No AI service or new dependency is needed; the coding agent supplies the review.
 */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

export const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generated = ['release/history.json', 'lib/core/constants/release_history.g.dart', 'web/release.json'];
const site = '574455f0-7d1a-4b99-ab18-18e79d65b648';
const canonical = 'https://flexiblelearning.gafarstechnologies.com';
const backendUrl = 'https://focus-mission-backend.onrender.com';
const categories = ['new', 'improved', 'fixed'];
const work = path.join(appRoot, '.release-work');
const hash = value => crypto.createHash('sha256').update(value).digest('hex');
const read = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const write = (file, data) => { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, JSON.stringify(data, null, 2) + '\n'); };
function run(command, args, cwd, options = {}) {
  return execFileSync(command, args, { cwd, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024, ...options });
}
export const git = (root, ...args) => run('git', args, root).trim();
function normalized(file, content, backend) {
  if (backend && ['package.json', 'package-lock.json'].includes(file)) {
    const data = JSON.parse(content);
    delete data.version;
    if (data.packages?.['']) delete data.packages[''].version;
    return JSON.stringify(data);
  }
  if (!backend && file === 'pubspec.yaml') return content.toString().replace(/^version:.*$/m, 'version: GENERATED');
  return content;
}
export function snapshot(root, ref = 'HEAD', backend = false) {
  const excluded = backend ? ['release.json'] : generated;
  const files = {};
  for (const file of git(root, 'ls-tree', '-r', '--name-only', ref).split('\n').sort()) {
    if (excluded.includes(file)) continue;
    const bytes = execFileSync('git', ['show', `${ref}:${file}`], { cwd: root, maxBuffer: 32 * 1024 * 1024 });
    files[file] = hash(normalized(file, bytes, backend));
  }
  return { commit: git(root, 'rev-parse', ref), digest: hash(JSON.stringify(files)), files };
}
export function nextVersion(previous, changes, breaking = false, approvedMajor = false) {
  if (!/^\d+\.\d+\.\d+$/.test(previous)) throw new Error('Invalid previous semantic version.');
  const [major, minor, patch] = previous.split('.').map(Number);
  if (breaking && !approvedMajor) throw new Error('Breaking change needs explicit major-release review.');
  if (breaking) return `${major + 1}.0.0`;
  if (changes.new?.length) return `${major}.${minor + 1}.0`;
  if (changes.improved?.length || changes.fixed?.length) return `${major}.${minor}.${patch + 1}`;
  throw new Error('No user-facing changes to release.');
}
export function publicHistory(history) {
  return { version: history.releases[0].version, releases: history.releases.map(r => ({
    version: r.version, previousVersion: r.previousVersion, releasedAt: r.releasedAt,
    title: r.title, changes: r.changes,
    source: { frontend: r.source.frontend.commit, backend: r.source.backend.commit },
  })) };
}
export function dartHistory(history) {
  // JSON is decoded by the model; base64 keeps arbitrary reviewed text safe in Dart.
  const data = Buffer.from(JSON.stringify(publicHistory(history))).toString('base64');
  return `/**\n * WHAT: Generated release data used by the public version history.\n * WHY: The website must use the canonical release/history.json version.\n * HOW: Generated by tool/release.mjs; do not edit by hand.\n */\n// ignore_for_file: dangling_library_doc_comments, slash_for_doc_comments\n\nconst releaseHistoryBase64 = '${data}';\n`;
}
function historyAt(root = appRoot) { return read(path.join(root, 'release/history.json')); }
function assertHistory(history) {
  const versions = new Set();
  history.releases.forEach((r, index) => {
    if (!/^\d+\.\d+\.\d+$/.test(r.version) || versions.has(r.version)) throw new Error('Invalid or duplicate release history.');
    versions.add(r.version);
    if (!r.title?.trim() || categories.some(c => !Array.isArray(r.changes[c]))) throw new Error('Invalid release notes.');
    if (history.releases[index + 1] && r.previousVersion !== history.releases[index + 1].version) throw new Error('Broken release history chain.');
  });
}
function backendRecord(entry) {
  return { version: entry.version, releasedAt: entry.releasedAt, source: entry.source.backend, validation: entry.validation };
}
function generate(history, backend) {
  assertHistory(history);
  write(path.join(appRoot, generated[0]), history);
  fs.writeFileSync(path.join(appRoot, generated[1]), dartHistory(history));
  write(path.join(appRoot, generated[2]), publicHistory(history));
  const pubspec = path.join(appRoot, 'pubspec.yaml');
  const version = history.releases[0].version;
  fs.writeFileSync(pubspec, fs.readFileSync(pubspec, 'utf8').replace(/^version:.*$/m, `version: ${version}+${history.releases.length}`));
  for (const name of ['package.json', 'package-lock.json']) {
    const file = path.join(backend, name); const data = read(file); data.version = version;
    if (data.packages?.['']) data.packages[''].version = version;
    write(file, data);
  }
  write(path.join(backend, 'release.json'), backendRecord(history.releases[0]));
}
function baseline(history) {
  // Only a post-verification deployed/v tag is a production baseline. A v tag
  // alone can be a prepared release whose deployment still needs to be retried.
  const tag = git(appRoot, 'tag', '--list', 'deployed/v*', '--sort=-version:refname').split('\n').filter(Boolean)[0];
  if (!tag) {
    const imported = history.releases.at(-1);
    if (!imported.provenance) throw new Error('No verified production baseline.');
    return imported;
  }
  const version = tag.replace('deployed/v', '');
  const entry = history.releases.find(r => r.version === version);
  if (!entry || git(appRoot, 'rev-parse', `${tag}^{commit}`) !== git(appRoot, 'rev-parse', `v${version}^{commit}`)) throw new Error('Production tag and history disagree.');
  return entry;
}
function changesSince(root, previous, backend) {
  const now = snapshot(root, 'HEAD', backend);
  const old = snapshot(root, previous.source[backend ? 'backend' : 'frontend'].commit, backend);
  const files = [...new Set([...Object.keys(old.files), ...Object.keys(now.files)])].filter(f => old.files[f] !== now.files[f]);
  return { source: now, files, commits: git(root, 'log', '--format=%h %s', `${old.commit}..HEAD`),
    diff: git(root, 'diff', '--no-ext-diff', old.commit, 'HEAD', '--', ...files) };
}
function inspect(backend) {
  const history = historyAt(); const previous = baseline(history);
  const frontend = changesSince(appRoot, previous, false); const server = changesSince(backend, previous, true);
  fs.mkdirSync(work, { recursive: true });
  fs.writeFileSync(path.join(work, 'frontend.diff'), frontend.diff);
  fs.writeFileSync(path.join(work, 'backend.diff'), server.diff);
  const report = { previousVersion: previous.version, frontend: { ...frontend, diff: '.release-work/frontend.diff' }, backend: { ...server, diff: '.release-work/backend.diff' } };
  write(path.join(work, 'inspection.json'), report);
  console.log(JSON.stringify({ previousVersion: previous.version, frontend: { digest: frontend.source.digest, files: frontend.files, commits: frontend.commits }, backend: { digest: server.source.digest, files: server.files, commits: server.commits }, review: '.release-work/inspection.json' }, null, 2));
  return report;
}
export function verifyReview(review, current, previous) {
  if (review.previousVersion !== previous || review.frontendDigest !== current.frontend.digest || review.backendDigest !== current.backend.digest) throw new Error('Release review is stale. Inspect and review the current diffs again.');
  if (!review.title?.trim() || !review.evidence?.length || categories.some(c => !Array.isArray(review.changes?.[c]))) throw new Error('Provide reviewed notes and code evidence, not raw filenames or commit messages.');
  if (typeof review.breaking !== 'boolean') throw new Error('Review whether the changes are breaking before choosing a version.');
  for (const note of categories.flatMap(c => review.changes[c])) if (typeof note !== 'string' || !note.trim()) throw new Error('Empty release note.');
}
function prepare(backend, reviewFile, approvedMajor) {
  const history = historyAt(); const entry = history.releases[0];
  const current = { frontend: snapshot(appRoot), backend: snapshot(backend, 'HEAD', true) };
  if (entry.source.frontend.digest === current.frontend.digest && entry.source.backend.digest === current.backend.digest) {
    console.log(`v${entry.version} already describes this source; no version bump.`); generate(history, backend); return entry;
  }
  const previous = baseline(history);
  if (entry.version !== previous.version) throw new Error(`Finish deploying prepared v${entry.version} before preparing another release.`);
  if (!reviewFile || !fs.existsSync(reviewFile)) throw new Error('Unreleased application changes detected. Run inspect, review both diffs, and supply --review <review.json>. See RELEASE.md.');
  const review = read(reviewFile); verifyReview(review, current, previous.version);
  const oldFrontend = previous.source.frontend.files || snapshot(appRoot, previous.source.frontend.commit).files;
  const oldBackend = previous.source.backend.files || snapshot(backend, previous.source.backend.commit, true).files;
  const changed = (now, old, pattern) => [...new Set([...Object.keys(now), ...Object.keys(old)])].some(f => pattern.test(f) && now[f] !== old[f]);
  const releasable = changed(current.frontend.files, oldFrontend, /^(lib\/|web\/|assets\/|tool\/|pubspec\.)/) || changed(current.backend.files, oldBackend, /^(src\/|server\.js|package(?:-lock)?\.json)/);
  if (!releasable) throw new Error('Only development/documentation changes; no public release is needed.');
  const version = nextVersion(previous.version, review.changes, review.breaking, approvedMajor);
  const next = { version, previousVersion: previous.version, releasedAt: new Date().toISOString(), title: review.title, changes: review.changes, source: current, reviewEvidence: review.evidence, validation: { status: 'pending' } };
  history.releases.unshift(next); generate(history, backend);
  console.log(`Prepared v${version}. Validation is required before deployment.`); return next;
}
function assertSource(root, expected, backend = false) {
  if (snapshot(root, 'HEAD', backend).digest !== expected.digest) throw new Error('Unreleased application changes detected. Run the Release Agent before deploying.');
  for (const [file, expectedHash] of Object.entries(expected.files)) {
    // Published archives never include unrelated worktree edits. Guard commands
    // on checkouts do inspect the actual files, so a raw dirty build is blocked.
    if (hash(normalized(file, fs.readFileSync(path.join(root, file)), backend)) !== expectedHash) throw new Error(`Source differs from the release: ${file}`);
  }
}
function check(root = appRoot, backend, allowDirty = false) {
  const history = historyAt(root); assertHistory(history); const entry = history.releases[0];
  if (entry.validation?.status !== 'passed') throw new Error('Release validation has not passed.');
  if (snapshot(root).digest !== entry.source.frontend.digest) throw new Error('Unreleased application changes detected. Run the Release Agent before deploying.');
  if (!allowDirty) assertSource(root, entry.source.frontend);
  if (fs.readFileSync(path.join(root, generated[1]), 'utf8') !== dartHistory(history) || JSON.stringify(read(path.join(root, generated[2]))) !== JSON.stringify(publicHistory(history))) throw new Error('Generated website version/history is stale.');
  if (!fs.readFileSync(path.join(root, 'pubspec.yaml'), 'utf8').includes(`version: ${entry.version}+${history.releases.length}\n`)) throw new Error('Build version differs from the release.');
  if (backend) {
    if (snapshot(backend, 'HEAD', true).digest !== entry.source.backend.digest) throw new Error('Backend source differs from the release.');
    if (!allowDirty) assertSource(backend, entry.source.backend, true);
    if (JSON.stringify(read(path.join(backend, 'release.json'))) !== JSON.stringify(backendRecord(entry))) throw new Error('Backend release evidence differs from the canonical history.');
  }
  console.log(`Release guard passed: v${entry.version}`); return entry;
}
function archive(repo, folder) {
  fs.mkdirSync(folder, { recursive: true });
  const tar = path.join(folder, 'source.tar'); run('git', ['archive', 'HEAD', '-o', tar], repo); run('tar', ['-xf', tar, '-C', folder], repo); fs.unlinkSync(tar);
}
function copy(root, destination, files) { for (const file of files) { fs.mkdirSync(path.dirname(path.join(destination, file)), { recursive: true }); fs.copyFileSync(path.join(root, file), path.join(destination, file)); } }
function validate(backend) {
  const history = historyAt(); const entry = history.releases[0];
  if (snapshot(appRoot).digest !== entry.source.frontend.digest || snapshot(backend, 'HEAD', true).digest !== entry.source.backend.digest) throw new Error('Source changed after preparation.');
  const uri = process.env.FOCUS_TEST_MONGO_URI || '';
  if (!/^mongodb:\/\/(127\.0\.0\.1|localhost):\d+\//.test(uri)) throw new Error('FOCUS_TEST_MONGO_URI must point to a disposable loopback replica set; integration tests may not be skipped.');
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'focus-release-'));
  const frontend = path.join(directory, 'frontend'); const server = path.join(directory, 'backend');
  archive(appRoot, frontend); archive(backend, server);
  copy(appRoot, frontend, [...generated, 'pubspec.yaml']); copy(backend, server, ['package.json', 'package-lock.json', 'release.json']);
  function checked(command, args, cwd, label) {
    console.log(`Validating ${label}...`);
    try { const output = run(command, args, cwd); fs.writeFileSync(path.join(directory, `${label}.log`), output); return output; }
    catch (error) { fs.writeFileSync(path.join(directory, `${label}.log`), String(error.stdout || '') + String(error.stderr || '')); throw new Error(`${label} failed. See ${directory}/${label}.log. No deployment performed.`); }
  }
  checked('node', ['--test', 'tool/release.test.mjs'], frontend, 'release-tests');
  checked('npm', ['ci', '--ignore-scripts', '--no-audit', '--no-fund'], server, 'backend-install');
  for (const file of Object.keys(entry.source.backend.files).filter(f => f.endsWith('.js'))) checked('node', ['--check', file], server, `syntax-${file.replaceAll('/', '-')}`);
  const tests = checked('node', ['--test', '--test-reporter=tap', ...fs.readdirSync(path.join(server, 'test')).filter(f => f.endsWith('.test.js')).map(f => `test/${f}`)], server, 'backend-tests');
  if (!/# skipped 0\b/.test(tests) || !/# fail 0\b/.test(tests)) throw new Error('Backend tests failed or were skipped. No deployment performed.');
  checked('flutter', ['pub', 'get'], frontend, 'pub-get');
  checked('flutter', ['analyze', '--no-pub'], frontend, 'analyze');
  const flutterTests = checked('flutter', ['test', '--no-pub', '--reporter', 'expanded'], frontend, 'flutter-tests');
  checked('flutter', ['build', 'web', '--release', '--no-pub'], frontend, 'build');
  // Revalidation after losing a temporary build must not rewrite a tagged
  // release or produce a second metadata commit for the same version.
  if (entry.validation.status !== 'passed') entry.validation = { status: 'passed', checkedAt: new Date().toISOString(), backendTests: Number(tests.match(/# tests (\d+)/)?.[1]), flutterTests: Number(flutterTests.match(/\+(\d+): All tests passed/)?.[1]), analysis: 'passed', build: 'passed', backendSyntax: 'passed', integrationTests: 'passed; no skips' };
  generate(history, backend); copy(backend, server, ['release.json']);
  checked('node', ['src/utils/releaseGuard.js'], server, 'backend-release-guard');
  const receipt = { version: entry.version, frontendDigest: entry.source.frontend.digest, backendDigest: entry.source.backend.digest, directory, frontend, backend: server,
    artifacts: Object.fromEntries(['index.html', 'main.dart.js', 'flutter_bootstrap.js', 'release.json', 'version.json'].map(f => [f, hash(fs.readFileSync(path.join(frontend, 'build/web', f)))])) };
  write(path.join(work, 'validation.json'), receipt);
  console.log(JSON.stringify(entry.validation)); return receipt;
}
function finalize(backend) {
  const entry = check(appRoot, backend, true); const receipt = read(path.join(work, 'validation.json'));
  if (receipt.frontendDigest !== entry.source.frontend.digest || receipt.backendDigest !== entry.source.backend.digest) throw new Error('Validation receipt is stale.');
  for (const [root, files] of [[backend, ['release.json', 'package.json', 'package-lock.json']], [appRoot, [...generated, 'pubspec.yaml']]]) {
    if (git(root, 'diff', '--cached', '--name-only')) throw new Error('Unrelated staged files must be unstaged before the release commit.');
    run('git', ['add', '--', ...files], root);
    if (git(root, 'diff', '--cached', '--name-only')) run('git', ['commit', '-m', `release: v${entry.version}`], root, { stdio: 'inherit' });
    const tag = `v${entry.version}`;
    if (!git(root, 'tag', '--list', tag)) run('git', ['tag', '-a', tag, '-m', `Focus Mission ${tag}; validated source recorded in release manifest`], root);
    else if (git(root, 'rev-parse', `${tag}^{commit}`) !== git(root, 'rev-parse', 'HEAD')) throw new Error(`${tag} already points to a different release. Never move a release tag.`);
  }
  return receipt;
}
async function verifyPublic(receipt, deployUrl) {
  for (const base of [canonical, deployUrl]) {
    for (const [file, expected] of Object.entries(receipt.artifacts)) {
      const response = await fetch(`${base}/${file}?release=${receipt.version}-${Date.now()}`);
      if (!response.ok || hash(Buffer.from(await response.arrayBuffer())) !== expected) throw new Error(`Public artifact mismatch: ${base}/${file}`);
    }
  }
}
async function checkBackend(entry, backend) {
  const response = await fetch(`${backendUrl}/api/health`, { signal: AbortSignal.timeout(45000) });
  const status = await response.json();
  if (!response.ok || status.database !== 'connected' || status.release?.version !== entry.version || status.release?.sourceDigest !== entry.source.backend.digest || status.release?.commit !== git(backend, 'rev-parse', 'HEAD')) throw new Error('Exact backend release is not healthy yet.');
}
async function deploy(backend, review, major) {
  const entry = prepare(backend, review, major);
  let receipt;
  const cached = path.join(work, 'validation.json');
  if (entry.validation?.status === 'passed' && fs.existsSync(cached)) {
    receipt = read(cached);
    if (receipt.frontendDigest !== entry.source.frontend.digest || receipt.backendDigest !== entry.source.backend.digest || !fs.existsSync(path.join(receipt.frontend, 'build/web/main.dart.js'))) receipt = null;
  }
  if (!receipt) receipt = validate(backend);
  receipt = finalize(backend);
  for (const [file, expected] of Object.entries(receipt.artifacts)) if (hash(fs.readFileSync(path.join(receipt.frontend, 'build/web', file))) !== expected) throw new Error('Validated build artifacts changed.');
  for (const root of [backend, appRoot]) {
    run('git', ['push', 'origin', 'HEAD:main', `v${entry.version}`], root, { stdio: 'inherit' });
    if (git(root, 'ls-remote', 'origin', 'refs/heads/main').split(/\s/)[0] !== git(root, 'rev-parse', 'HEAD')) throw new Error('Remote main differs from the release.');
  }
  // The backend health record is emitted only after its startup source guard.
  let ready = false;
  for (let attempt = 0; attempt < 60; attempt++) {
    try { await checkBackend(entry, backend); ready = true; break; } catch { /* Render may be restarting; retain the bounded wait. */ }
    if (attempt % 6 === 0) console.log('Waiting for the exact validated backend release...');
    await new Promise(resolve => setTimeout(resolve, 10000));
  }
  if (!ready) throw new Error('Exact backend release is not healthy yet; frontend publication is blocked. Retry deploy after Render is ready.');
  const identity = JSON.parse(run('netlify', ['api', 'getSite', '--data', JSON.stringify({ site_id: site })], receipt.frontend));
  if (identity.id !== site || identity.ssl_url !== canonical) throw new Error('Netlify site identity differs from the configured production app.');
  const result = JSON.parse(run('netlify', ['deploy', '--dir=build/web', '--prod', '--no-build', `--site=${site}`, '--message', `Focus Mission v${entry.version}`, '--json'], receipt.frontend));
  write(path.join(work, 'deployment.json'), result);
  const url = result.deploy_url || result.deploy_ssl_url;
  if (!url) throw new Error('Netlify did not return a deployment URL.');
  await verifyPublic(receipt, url);
  for (const root of [backend, appRoot]) {
    const tag = `deployed/v${entry.version}`;
    if (!git(root, 'tag', '--list', tag)) run('git', ['tag', '-a', tag, '-m', `Verified production release ${entry.version}; Netlify ${result.deploy_id}`], root);
    run('git', ['push', 'origin', tag], root, { stdio: 'inherit' });
  }
  console.log(`Verified production v${entry.version}: ${canonical}`);
}
async function main() {
  const args = process.argv.slice(2); const command = args.shift();
  const option = flag => args.includes(flag) ? args[args.indexOf(flag) + 1] : undefined;
  const backend = path.resolve(option('--backend') || path.join(appRoot, '../focus_mission_backend'));
  try {
    if (command === 'inspect') inspect(backend);
    else if (command === 'prepare-release') prepare(backend, option('--review'), args.includes('--approve-major'));
    else if (command === 'validate') validate(backend);
    else if (command === 'check') check(appRoot, args.includes('--frontend-only') ? undefined : backend);
    else if (command === 'check-backend') await checkBackend(check(appRoot, backend), backend);
    else if (command === 'verify-public') {
      const entry = check(appRoot, backend);
      const artifacts = Object.fromEntries(['index.html', 'main.dart.js', 'flutter_bootstrap.js', 'release.json', 'version.json'].map(f => [f, hash(fs.readFileSync(path.join(appRoot, 'build/web', f)))]));
      await verifyPublic({ version: entry.version, artifacts }, option('--url') || canonical);
    }
    else if (command === 'deploy') await deploy(backend, option('--review'), args.includes('--approve-major'));
    else throw new Error('Use inspect, prepare-release, validate, check or deploy. See RELEASE.md.');
  } catch (error) { console.error(`Production deployment blocked: ${error.message}`); process.exitCode = 1; }
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main();
